<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-G14U564" name="com.yzc.hrsystem.test.MyRegisterTest" tests="7" failures="1" timestamp="30 七月 2018 02:07:27 GMT" time="107.769" errors="0">
  <testcase name="registerTest" time="14.383" classname="com.yzc.hrsystem.test.MyRegisterTest"/>
  <testcase name="registerTest" time="14.356" classname="com.yzc.hrsystem.test.MyRegisterTest"/>
  <testcase name="registerTest" time="14.201" classname="com.yzc.hrsystem.test.MyRegisterTest"/>
  <testcase name="registerTest" time="19.129" classname="com.yzc.hrsystem.test.MyRegisterTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:304)
	at org.testng.Assert.assertEquals(Assert.java:314)
	at com.yzc.hrsystem.test.MyRegisterTest.registerTest(MyRegisterTest.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- registerTest -->
  <testcase name="registerTest" time="14.263" classname="com.yzc.hrsystem.test.MyRegisterTest"/>
  <testcase name="registerTest" time="16.407" classname="com.yzc.hrsystem.test.MyRegisterTest"/>
  <testcase name="registerTest" time="15.030" classname="com.yzc.hrsystem.test.MyRegisterTest"/>
</testsuite> <!-- com.yzc.hrsystem.test.MyRegisterTest -->
